version: 2.1
jobs:
  update-jira-statuses:
      docker: 
        - image: cimg/python:3.10.4
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - run:
            cd ~/project/.circleci/scripts/
        - run:    
            pip install PyGithub
        - run:    
            pip install jira
        - run:    
            python /project/.circleci/scripts/jira_test.py $jira_user $jira_api_token $jira_server_url $github_api_token $github_project


# Orchestrate our job run sequence
workflows:
  jira_status_update:
    jobs:
      - update-jira-statuses