version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python:3.10.4
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/jonathanswift82/circleCiTester/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  update-jira-statuses:
    environment:
      jira_user: $jira_user
      jira_apikey: $jira_apikey
      jira_server_URL: $jira_server_URL
      github_Token: $github_Token
      github_project: $github_project
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo <parameter.jira_user> $jira_user!

workflows:
  my-custom-workflow:
    jobs:
      - update-jira-statuses