version: 2.1
jobs:
  build:
  update-jira-statuses:
      docker: 
        - image: cimg/python:3.10.4
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      environment:
        jira_user: $jira_user
        jira_api_token: $jira_api_token
        jira_server_url: $jira_server_url
        github_api_token: $github_api_token
        github_project: $github_project
        1jira_user: ${jira_user}
        1jira_api_token: ${jira_api_token}
        1jira_server_url: ${jira_server_url}
        1github_api_token: ${github_api_token}
        1github_project: ${github_project}
      steps:
        - checkout
        - run:
            sh -c env
            echo "test1"
            cd ~/project/.circleci/scripts/
            pip install PyGithub
            pip install jira
            python ./jira_test.py jira_user jira_api_token jira_server_url github_api_token
            python ./jira_test.py $jira_user $jira_api_token $jira_server_url $github_api_token
            python ./jira_test.py ${jira_user} ${jira_api_token} ${jira_server_url} ${github_api_token} ${github_project}
            python ./jira_test.py 1jira_user 1jira_api_token 1jira_server_url 1github_api_token 1github_project
            python ./jira_test.py $1jira_user $1jira_api_token $1jira_server_url $1github_api_token $1github_project


# Orchestrate our job run sequence
workflows:
  jira_status_update:
    jobs:
      - update-jira-statuses