version: 2.1
​
jobs:
  update-jira-statuses:
    docker:
      - image: circleci/python:3.8.3
    parameters:
      jira_user:
        type: string
      jira_api_token:
        type: string
      jira_server_url:
        type: string
      github_api_token:
        type: string
      github_project:
        type: string          
    steps:
      - run: echo << parameters.userProd >>
​
workflows:
  my-workflow:
    jobs:
      - update-jira-statuses:
          jira_user: jonathanswift82@gmail.com
          jira_api_token: 2R4hrboo5BTJtN1uAvc9B081
          jira_server_url: https://jiracircleciintegration.atlassian.net
          github_api_token: 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
          github_project: circleCiTester