version: 2.1
​
jobs:
  update-jira-statuses:
    docker:
      - image: circleci/python:3.8.3
    parameters:
      jira_user: $jira_user
        type: string
      jira_api_token: $jira_api_token
        type: string
      jira_server_url: $jira_server_url
        type: string
      github_api_token: $github_api_token
        type: string
      github_project: $github_project
        type: string          
    steps:
      - run: echo << parameters.userProd >>
          name: jira_status_update
          command: |
            cd ~/project/.circleci/scripts/
            pip3 install PyGithub
            pip3 install jira
            pip3 install python-dotenv
            echo << parameters.jira_user >> << parameters.jira_api_token >> << parameters.jira_server_url >> << parameters.github_api_token >> << parameters.github_project >>
            python3 jira_test.py $DD_API_KEY $DD_APPLICATION_KEY << parameters.jira_user >>
​
workflows:
  workflow-update-jira-statuses:
    jobs:
      - update-jira-statuses:
          jira_user: $jira_user
          jira_api_token: $jira_api_token
          jira_server_url: $jira_server_url
          github_api_token: $github_api_token
          github_project: $github_api_token