version: 2.1
jobs:
  update-jira-statuses:
      docker: 
        - image: cimg/python:3.10.4
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - run:
            name: "Updating Jira Status"
            command: |
              cd ~/project/.circleci/scripts/ 
              pip install PyGithub
              pip install jira 
              python jira_test.py $jira_user $jira_api_token $jira_server_url $github_api_token $github_project

# Orchestrate our job run sequence
workflows:
  jira_status_update:
    jobs:
      filters:
        branches:
          only:
            - /pre-release\/.*/
            - /release\/.*/
      - update-jira-statuses