version: 2.1
​
jobs:
  update-jira-statuses:
    docker:
      - image: circleci/python:3.8.3 
    steps:
      - run: echo << parameters.userProd >>
          name: jira_status_update
          command: |
            cd ~/project/.circleci/scripts/
            pip3 install PyGithub
            pip3 install jira
            pip3 install python-dotenv
            echo << $jira_user >> << $jira_api_token >> << $jira_server_url >> << $github_api_token >> << $github_project >>
            python3 jira_test.py $jira_user $jira_api_token $jira_server_url $github_api_token $github_project
​
workflows:
  workflow-update-jira-statuses:
    jobs:
      - update-jira-statuses:
          