version: 2.1
jobs:
  update-jira-statuses:
      docker: 
        - image: cimg/python:3.10.4
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
          path: $github_project
        - run:
            echo $jira_user


# Orchestrate our job run sequence
workflows:
  jira_status_update:
    jobs:
      - update-jira-statuses